server:
  port: 8888

spring:
  application:
    name: msvc-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/
        git:  # Elimina o desactiva la configuración de Git
          uri: # D