version: '3.8'

services:
  config:
    build:
      context: ./microservice-config
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./configurations:/configurations


  eureka:
    build:
      context: ./microservice-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config


  gateway:
    build:
      context: ./microservice-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka

  student:
    build:
      context: ./microservice-student
    container_name: student-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - config
      - activemq
      - students-database


  course:
    build:
      context: ./microservice-course
    container_name: course-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - config
      - courses-database

  aws:
    build:
      context: ./microservice-aws
    container_name: aws-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_ACCESS_KEY=xxx
      - AWS_SECRET_KEY=xxx
      - AWS_REGION=us-east-1
    depends_on:
      - eureka
      - activemq
      - config


  students-database:
    image: mysql:8.0
    container_name: students-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentDb


  courses-database:
    image: mysql:8.0
    container_name: courses-database
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coursesDb

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
