version: '3.8'

networks:
  mynetwork:
    driver: bridge
services:
  config:
    build:
      context: ./microservice-config
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mynetwork


  eureka:
    build:
      context: ./microservice-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config
    networks:
      - mynetwork


  gateway:
    build:
      context: ./microservice-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - eureka
    networks:
      - mynetwork

  student:
    build:
      context: ./microservice-student
    container_name: student-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - eureka
      - config
      - activemq
      - students-database
    networks:
      - mynetwork


  course:
    build:
      context: ./microservice-course
    container_name: course-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - eureka
      - config
      - courses-database
    networks:
      - mynetwork

  aws:
    build:
      context: ./microservice-aws
    container_name: aws-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - AWS_ACCESS_KEY=xxx
      - AWS_SECRET_KEY=xxx
      - AWS_REGION=us-east-1
    depends_on:
      - eureka
      - activemq
      - config
    networks:
      - mynetwork


  students-database:
    image: mysql:8.0
    container_name: students-database
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentDb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork


  courses-database:
    image: mysql:8.0
    container_name: courses-database
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coursesDb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - mynetwork
