version: '3.8'

services:
  config:
    build:
      context: ./microservice-config
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config
  eureka:
    build:
      context: ./microservice-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config

  gateway:
    build:
      context: ./microservice-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka

  student:
    build:
      context: ./microservice-student
    container_name: student-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/studentsdb
    depends_on:
      - eureka
      - database

  course:
    build:
      context: ./microservice-course
    container_name: course-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/coursesdb
    depends_on:
      - eureka
      - database

  aws:
    build:
      context: ./microservice-aws
    container_name: aws-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka

  database:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coursesdb

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"