spring:
  application:
    name: msvc-student

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://students-database:3306/studentDb
    username: root
    password: root # Asegúrate de usar la misma contraseña que definiste en el contenedor MySQL.
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    in-memory: false

  config:
    import: configserver:http://config-server:8888

messaging:
  consumer-id: ${spring.application.name}
  consumers:
    queues:
      msvc-student: VirtualTopic.msvc.student
  producers:
    topics:
      msvc-student: VirtualTopic.msvc.student
      msvc-aws-s3: VirtualTopic.msvc.aws.s3

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

