spring:
  application:
    name: msvc-aws
  config:
    import: optional:configserver:http://config-server:8888

destination:
  folder: /static/

activemq:
  broker-url: tcp://activemq:61616
  user: admin
  password: admin

aws:
  region: ${AWS_REGION}
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}

messaging:
  consumer-id: ${spring.application.name}
  consumers:
    queues:
      msvc-aws-s3: VirtualTopic.msvc.aws.s3
  producers:
    topics:
      msvc-student: VirtualTopic.msvc.student
      msvc-aws-s3: VirtualTopic.msvc.aws.s3

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
