spring:
  datasource:
    url: jdbc:mysql://database:3306/coursesdb
    username: root
    password: root
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka
